/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javagtk2_GTK */

#ifndef _Included_javagtk2_GTK
#define _Included_javagtk2_GTK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javagtk2_GTK
 * Method:    __initialise
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javagtk2_GTK__1_1initialise
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     javagtk2_GTK
 * Method:    main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javagtk2_GTK_main
  (JNIEnv *, jclass);

/*
 * Class:     javagtk2_GTK
 * Method:    exit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javagtk2_GTK_exit
  (JNIEnv *, jclass, jint);

/*
 * Class:     javagtk2_GTK
 * Method:    mainLevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javagtk2_GTK_mainLevel
  (JNIEnv *, jclass);

/*
 * Class:     javagtk2_GTK
 * Method:    mainQuit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javagtk2_GTK_mainQuit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
